experiment:
  config: configs/experiments/rouse_base.yaml

data:
  prefer_hdf5: true

analysis:
  video: false
  potential: true
  score: false

output:
  dir: outputs
  experiment_name: rouse_base
  histogram_file: rouse_base_potential_histogram.png
