experiment:
  config: configs/experiments/rouse_video.yaml

analysis:
  video: true
  potential: false
  score: false

video:
  framerate: 24

output:
  dir: outputs
  experiment_name: rouse_raw
  frame_dirname: frames
  gif_file: rouse_raw_first_5tau.gif
  mp4_file: rouse_raw_first_5tau.mp4
