experiment:
  config: configs/experiments/rouse_video.yaml

analysis:
  video: true
  potential: false
  score: false

video:
  framerate: 24

output:
  dir: outputs
  experiment_name: rouse_video
  frame_dirname: frames
  gif_file: rouse_video_first_5tau.gif
