experiment:
  config: configs/experiments/rouse_lennard_jones_video.yaml

data:
  prefer_hdf5: true

analysis:
  video: true
  potential: false
  score: false

video:
  framerate: 60
  center: true
  normalize: true
  normalization_eps: 1.0e-6

output:
  dir: outputs
  experiment_name: rouse_lennard_jones_video
  frame_dirname: frames
  gif_file: rouse_lennard_jones_video_burnin5tau_record10tau.gif
