experiment:
  config: configs/experiments/rouse_base_video.yaml

data:
  prefer_hdf5: true

analysis:
  video: true
  potential: false
  score: false

video:
  framerate: 60

output:
  dir: outputs
  experiment_name: rouse_base_video
  frame_dirname: frames
  gif_file: rouse_base_video_first_5tau.gif
