extends: nbody_polymer_cnf_egnn_rouse_hdf5_base.yaml

experiment:
  name: nbody_polymer_confinement_cnf_egnn_rouse_hdf5

data:
  source_dir: /orcd/scratch/orcd/006/davidgoh/juliaproj/outputs/rouse_confinement/b92d4a875325/trajectories
  physics_params: [1.0, 1.0, 3.0, 0.0, 0.05, 1.0, 0.4, 2.5, 1.0, 1.0, 0.0, 0.02, 1.0, 0.4, 12.0, 2.5, 1.0, 1.0, 0.02, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 4.0, 0.0, 1.0, 0.0]
