extends: nbody_polymer_cnf_egnn_rouse_hdf5_base.yaml

experiment:
  name: nbody_polymer_cnf_egnn_rouse_hdf5

data:
  source_dir: /orcd/scratch/orcd/006/davidgoh/juliaproj/outputs/rouse_base/e6a343e8490d/trajectories
  physics_params: [1.0, 1.0, 3.0]
