extends: nbody_polymer_cnf_egnn_rouse_hdf5_base.yaml

experiment:
  name: nbody_polymer_cnf_egnn_rouse_hdf5

data:
  source_dir: /orcd/scratch/orcd/006/davidgoh/juliaproj/outputs/rouse_base/f5ecf974b2a8/trajectories
  physics_params: [0.25, 1.0, 3.0]
